title: Zhaojin Chu
description: Personal Website
baseurl: ""
url: https://zhaojinchu.github.io/

theme: cvless

# site settings
taglong: Student at Dubai College
tagshort: 

# author settings
author:
  name: Zhaojin Chu
  email: zhaojin.chu07@gmail.com
photo: assets/files/photo.jpg
address: 
phone: +971 58 188 6719

# social media links
social:
  #facebook: username
  github: zhaojinchu
  #instagram: username
  linkedin: zhaojin-chu-ab0184287
  stackoverflow: 33251512/zhaojin-chu
  #x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md

# setting default paths
defaults:
  - scope:
      path: "assets/"