title: Zhaojin Chu
description: Building human-centered AI systems, resilient hardware, and joyful learning experiences.
baseurl: ""
url: https://zhaojinchu.github.io/

theme: cvless

# site settings
taglong: Electrical & Computer Engineering @ Carnegie Mellon University
tagshort: ECE @ Carnegie Mellon

# author settings
author:
  name: Zhaojin Chu
  email: zhaojinc@andrew.cmu.edu
photo: assets/files/photo.jpg
address:
phone: +1 (412) 657-5072

# social media links
social:
  github: zhaojinchu
  linkedin: zhaojinc
  stackoverflow: 33251512/zhaojin-chu

collections:
  projects:
    output: true
    permalink: /projects/:slug/

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: "assets/files"
    values:
      sitemap: false
